version: "3.6"
services:
  web:
    image: craftcms/nginx:8.0-dev
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    env_file: .env
    depends_on: 
        - mysql
  console:
    image: craftcms/cli:8.0-dev
    volumes:
      - ./app:/app
    env_file: .env
    command: ["./craft", "queue/listen"]
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: SuperPassword123456!
      MYSQL_DATABASE: dev_craftcms
      MYSQL_USER: craftcms
      MYSQL_PASSWORD: SecretPassword
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
volumes:
  db_data:
